<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_60c61676de5dd',
        'title' => 'Couts',
        'fields' => array(
            array(
                'key' => 'field_60c616858c353',
                'label' => 'Cout',
                'name' => 'atgp_cours_cout',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => '',
                'max' => '',
                'step' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'taxonomy',
                    'operator' => '==',
                    'value' => 'atgp-ctx-group',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_60bfea28b82ff',
        'title' => 'Inscriptions',
        'fields' => array(
            array(
                'key' => 'field_60c359e1ee3a0',
                'label' => 'Etat civil',
                'name' => 'atgp_group_etat_civil',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'row',
                'sub_fields' => array(
                    array(
                        'key' => 'field_60bfea45fedb9',
                        'label' => 'Nom',
                        'name' => 'atgp_nom',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_60bfea89fedba',
                        'label' => 'Prénom',
                        'name' => 'atgp_prenom',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_60bfeaa2fedbb',
                        'label' => 'Sexe',
                        'name' => 'atgp_sexe',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'Masculin' => 'Masculin',
                            'Féminin' => 'Féminin',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                        'save_other_choice' => 0,
                    ),
                    array(
                        'key' => 'field_60bfeadffedbc',
                        'label' => 'Date de naissance',
                        'name' => 'atgp_date_de_naissance',
                        'type' => 'date_picker',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'display_format' => 'd/m/Y',
                        'return_format' => 'd/m/Y',
                        'first_day' => 1,
                    ),
                    array(
                        'key' => 'field_60bfeb1bfedbd',
                        'label' => 'Adresse',
                        'name' => 'atgp_adresse',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_60bfeb3dfedbe',
                        'label' => 'Code postal',
                        'name' => 'atgp_code_postal',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                    ),
                    array(
                        'key' => 'field_60bfeb9afedbf',
                        'label' => 'Ville',
                        'name' => 'atgp_ville',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_60bfebf3fedc1',
                        'label' => 'Téléphone mobile',
                        'name' => 'atgp_tel',
                        'type' => 'number',
                        'instructions' => 'Le téléphone mobile est nécessaire pour recevoir les infos du club par sms',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                    ),
                    array(
                        'key' => 'field_60bfec37fedc2',
                        'label' => 'Téléphone fixe',
                        'name' => 'atgp_tel_fixe',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                    ),
                    array(
                        'key' => 'field_60bfec69fedc3',
                        'label' => 'Courriel',
                        'name' => 'atgp_courriel',
                        'type' => 'email',
                        'instructions' => 'L’adresse mail est nécessaire pour que vous puissiez recevoir la licence sportive et les informations du club.
    Le dossier à imprimer sera envoyé à cette adresse.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_60c35a75ff823',
                'label' => 'En cas d\'urgence',
                'name' => 'atgp_group_urgence',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'row',
                'sub_fields' => array(
                    array(
                        'key' => 'field_60c22e034d461',
                        'label' => 'En cas d\'urgence...',
                        'name' => '',
                        'type' => 'message',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '<h3>Personne à prévenir en cas d\'urgence</h3>',
                        'new_lines' => 'wpautop',
                        'esc_html' => 0,
                    ),
                    array(
                        'key' => 'field_60c22f3097aad',
                        'label' => 'Nom',
                        'name' => 'atgp_nom_urgence',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_60c22f4c97aae',
                        'label' => 'Prénom',
                        'name' => 'atgp_prenom_urgence',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_60c22f6097aaf',
                        'label' => 'Téléphone 1',
                        'name' => 'atgp_tel_urgence',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                    ),
                    array(
                        'key' => 'field_60c22f8e97ab0',
                        'label' => 'Téléphone 2',
                        'name' => 'atgp_fixe_urgence',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_60c358ee943e5',
                'label' => 'Adhésion',
                'name' => 'atgp_group_adhesion',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_60bfebb5fedc0',
                        'label' => 'Type d\'adhésion',
                        'name' => 'atgp_type_dadhesion',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'Nouvelle adhésion' => 'Nouvelle adhésion',
                            'Renouvellement' => 'Renouvellement',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                        'save_other_choice' => 0,
                    ),
                    array(
                        'key' => 'field_60c35741fed27',
                        'label' => 'Numéro de licence',
                        'name' => 'atgp_licence',
                        'type' => 'text',
                        'instructions' => 'Vous retrouverez le numéro de licence dans le mail envoyé par la FFME à votre adresse de contact, en septembre de l\'année précédente. 
    Si vous n\'avez plus cette information, vous pouvez la retrouver en allant sur le site :
    <a href="https://licencie.ffme.fr/" target="_blank">https://licencie.ffme.fr/</a>
    (cliquez sur mot de passe oublié si besoin)',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_60bfebb5fedc0',
                                    'operator' => '==',
                                    'value' => 'Renouvellement',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_60c35c310470c',
                        'label' => 'Certificat médical',
                        'name' => 'atgp_group_adhesion_group_certificat',
                        'type' => 'group',
                        'instructions' => '<strong>le certificat médical doit mentionner "apte à la compétition"</strong>.<br>
    Le certificat médical est <strong>valable 3 ans</strong>(date à date).<br>
    Pour les renouvellements d\'inscription de cette année, même si votre certificat est encore valide, nous vous demandons de poster un scan en utilisant les champs ci-dessous. 
    (il ne sera pas demandé l\'année prochaine si il est toujours valide)',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_60c35c090470b',
                                'label' => 'Document scanné',
                                'name' => 'atgp_group_adhesion_certificat_file',
                                'type' => 'file',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'library' => 'uploadedTo',
                                'min_size' => '',
                                'max_size' => 5,
                                'mime_types' => '',
                            ),
                            array(
                                'key' => 'field_60c35c6e0470d',
                                'label' => 'Date du certificat',
                                'name' => 'atgp_group_adhesion_certificat_date',
                                'type' => 'date_picker',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'display_format' => 'd/m/Y',
                                'return_format' => 'd/m/Y',
                                'first_day' => 1,
                            ),
                            array(
                                'key' => 'field_60c3fe09e64d0',
                                'label' => 'Nom du médecin',
                                'name' => 'atgp_group_adhesion_certificat_medecin',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_60c0019497a89',
                'label' => 'Cours',
                'name' => 'atgp_group_cours',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_60c3601d3eeea',
                        'label' => 'Choix du cours',
                        'name' => '',
                        'type' => 'message',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '<a href="https://autangrimper.fr/horaires-calendriers/" target="_blank">Voir horaires et références en cliquant ici</a> (ouverture dans une nouvelle fenêtre).
    Si vous choisissez une inscription sur 2 créneaux, 60€ seront automatiquement retirés du prix (vous ne payez la licence qu\'une fois).
    <strong>Après avoir choisi votre (vos) créneaux, cliquez sur le bouton "Mettre à jour le montant" en bas de page.</strong>',
                        'new_lines' => 'wpautop',
                        'esc_html' => 0,
                    ),
                    array(
                        'key' => 'field_60c001b397a8a',
                        'label' => 'Dans quel groupe souhaitez-vous inscrire l\'adhésion ?',
                        'name' => 'atgp_group',
                        'type' => 'taxonomy',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'taxonomy' => 'atgp-ctx-group',
                        'field_type' => 'checkbox',
                        'add_term' => 0,
                        'save_terms' => 1,
                        'load_terms' => 0,
                        'return_format' => 'object',
                        'multiple' => 0,
                        'allow_null' => 0,
                    ),
                    array(
                        'key' => 'field_60c22c3f4d45f',
                        'label' => 'Autres souhaits de créneaux',
                        'name' => 'atgp_group_voeux',
                        'type' => 'group',
                        'instructions' => 'Si il ne reste plus de place sur le créneau choisi à l\'étape précédente, merci d\'ajouter vos souhaits ci-dessous dans l\'ordre de préférence.
    Nous ferons au mieux en fonction des places disponibles',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_60c22d3f4d460',
                                'label' => 'Voeux 1',
                                'name' => 'atgp_group_voeux_item1',
                                'type' => 'taxonomy',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'taxonomy' => 'atgp-ctx-group',
                                'field_type' => 'select',
                                'allow_null' => 0,
                                'add_term' => 0,
                                'save_terms' => 0,
                                'load_terms' => 0,
                                'return_format' => 'object',
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_60c379b40c199',
                                'label' => 'Voeux 2',
                                'name' => 'atgp_group_voeux_item2',
                                'type' => 'taxonomy',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'taxonomy' => 'atgp-ctx-group',
                                'field_type' => 'select',
                                'allow_null' => 0,
                                'add_term' => 0,
                                'save_terms' => 0,
                                'load_terms' => 0,
                                'return_format' => 'object',
                                'multiple' => 0,
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_60c003af97a8d',
                'label' => 'Assurance',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '<h3>Information relative à l\'assurance</h3>
    L\'assurance corporelle est comprise dans le coût d\'adhésion.
    Pour toutes souscriptions à des options d\'assurance, elles sont à votre charge et doivent être initier par vos soins auprès de la FFME.
    Plus d\'informations sur le site <a href="https://www.ffme.fr/ffme/licence/#assurance" target="_blank">https://www.ffme.fr/ffme/licence</a>',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_60c35ab2e3911',
                'label' => 'Coût',
                'name' => 'atgp_group_cout',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'row',
                'sub_fields' => array(
                    array(
                        'key' => 'field_60c004b197a8f',
                        'label' => 'Réductions',
                        'name' => 'atgp_reductions',
                        'type' => 'group',
                        'instructions' => '<strong>Après avoir choisi une éventuelle réduction ci-dessous, cliquez sur le bouton "Mettre à jour le montant" en bas de page.</strong>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_60c004ca97a90',
                                'label' => 'Type de réduction',
                                'name' => 'atgp_type_reduction',
                                'type' => 'checkbox',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'atgp-reduc-1' => '-30€ sur le 3eme adhérent d’une même famille.(1 seule réduction par famille)',
                                    'atgp-reduc-2' => '-10% pour un membre Conseil d’administration, ou du Bureau de l’association',
                                ),
                                'allow_custom' => 0,
                                'default_value' => array(
                                ),
                                'layout' => 'vertical',
                                'toggle' => 0,
                                'return_format' => 'array',
                                'save_custom' => 0,
                            ),
                            array(
                                'key' => 'field_60c36904888b0',
                                'label' => 'Autres membres de la famille si 3eme membre',
                                'name' => 'atgp_reduction_autres_membres',
                                'type' => 'relationship',
                                'instructions' => 'Sélectionnez les 2 autres membres de votre famille ayant rempli un dossier d\'inscription',
                                'required' => 1,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_60c004ca97a90',
                                            'operator' => '==',
                                            'value' => 'atgp-reduc-1',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'post_type' => array(
                                    0 => 'atgp-member',
                                ),
                                'taxonomy' => '',
                                'filters' => array(
                                    0 => 'search',
                                ),
                                'elements' => '',
                                'min' => 2,
                                'max' => 2,
                                'return_format' => 'object',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_60c005e597a91',
                        'label' => 'Total',
                        'name' => 'atgp_total',
                        'type' => 'number',
                        'instructions' => 'Tarif cours - réduction(s)',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Cliquez sur le bouton "Mettre à jour le montant en pied de page"',
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                    ),
                    array(
                        'key' => 'field_60c32a5eda844',
                        'label' => 'Mode de paiement',
                        'name' => 'atgp_paiement',
                        'type' => 'group',
                        'instructions' => '<strong>Le paiement se fait exclusivement par chèque</strong>, et peut être réparti sur 3 avec l\'échéancier suivant :
    Chèque 1, Septembre : <strong>Montant minimum de 80€</strong><br>
    Chèque 2, Début Novembre<br>
    Chèque 3, Début Février',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_60c33c2a84300',
                                'label' => 'Montant chèque 1',
                                'name' => 'atgp_echeancier_1_montant',
                                'type' => 'number',
                                'instructions' => 'Chèque 1, Septembre : <strong>Montant minimum de 80€</strong><br>
    <strong>cliquez sur le bouton "Mettre à jour le montant" en bas de page, avant de saisir le montant du chèque</strong>',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => 80,
                                'max' => '',
                                'step' => '',
                            ),
                            array(
                                'key' => 'field_60c33c7384301',
                                'label' => 'Numéro chèque 1',
                                'name' => 'atgp_echeancier_1_numero',
                                'type' => 'number',
                                'instructions' => 'Numéro du chèque',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                            ),
                            array(
                                'key' => 'field_60c33d1584302',
                                'label' => 'Paiement en 3 fois',
                                'name' => 'paiement_en_3_fois',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ),
                            array(
                                'key' => 'field_60c33d3184303',
                                'label' => 'Montant chèque 2',
                                'name' => 'atgp_echeancier_2_montant',
                                'type' => 'number',
                                'instructions' => 'Chèque 2, encaissé début Novembre',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_60c33d1584302',
                                            'operator' => '==',
                                            'value' => '1',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                            ),
                            array(
                                'key' => 'field_60c33d3784304',
                                'label' => 'Numéro chèque 2',
                                'name' => 'atgp_echeancier_2_numero',
                                'type' => 'number',
                                'instructions' => 'Numéro du chèque 2',
                                'required' => 1,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_60c33d1584302',
                                            'operator' => '==',
                                            'value' => '1',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                            ),
                            array(
                                'key' => 'field_60c33d9584305',
                                'label' => 'Montant chèque 3',
                                'name' => 'atgp_echeancier_3_montant',
                                'type' => 'number',
                                'instructions' => 'Chèque 3, encaissé début Février',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_60c33d1584302',
                                            'operator' => '==',
                                            'value' => '1',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                            ),
                            array(
                                'key' => 'field_60c33db884307',
                                'label' => 'Numéro chèque 3',
                                'name' => 'atgp_echeancier_3_numero',
                                'type' => 'number',
                                'instructions' => 'Numéro du chèque 3',
                                'required' => 1,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_60c33d1584302',
                                            'operator' => '==',
                                            'value' => '1',
                                        ),
                                        array(
                                            'field' => 'field_60c33d9584305',
                                            'operator' => '>',
                                            'value' => '1',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_60c3f577d4a62',
                'label' => 'Conditions',
                'name' => 'atgp_conditions',
                'type' => 'true_false',
                'instructions' => 'Je reconnais avoir pris connaissance du <a href="https://autangrimper.fr/reglement-interieur/" target="_blank" title="consulter le règlement intérieur">règlement intérieur</a> disponible et en accepte les conditions de celui-ci.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Oui',
                'ui_off_text' => 'Non',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'atgp-member',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_60c91a42812f2',
        'title' => 'Options Config',
        'fields' => array(
            array(
                'key' => 'field_60c91a5d7c44c',
                'label' => 'Adresse mail d\'envoi',
                'name' => 'atgp_option_config_mail',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_60c926308fcec',
                'label' => 'Téléphone de contact',
                'name' => 'atgp-tel-contact',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-configuration',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_60c62ad656afb',
        'title' => 'Réductions',
        'fields' => array(
            array(
                'key' => 'field_60c92ed6e0a93',
                'label' => 'Liste des réductions',
                'name' => 'atgp_reduc',
                'type' => 'repeater',
                'instructions' => 'Le calcul du coût sera en fonction de l\'ordre des réductions, et du type de réduction (fixe ou %)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_60c92e92e0a92',
                'min' => 0,
                'max' => 0,
                'layout' => 'row',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_60c92e0fe0a91',
                        'label' => 'ID',
                        'name' => 'atgp_reduc_id',
                        'type' => 'text',
                        'instructions' => 'ID represente le numéro de la réduction :
    <em>Exemple : atgp-reduc-1</em>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'atgp-reduc-{ID}',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_60c92e92e0a92',
                        'label' => 'Label',
                        'name' => 'atgp_reduc_label',
                        'type' => 'text',
                        'instructions' => '<em>Exemple : 3eme adhérent d\'une même famille</em>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_60c62adb0e2fe',
                        'label' => 'Type de réduction',
                        'name' => 'atgp_reduc_type',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'fixe' => 'fixe',
                            'pourcentage' => 'pourcentage',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'vertical',
                        'return_format' => 'value',
                        'save_other_choice' => 0,
                    ),
                    array(
                        'key' => 'field_60c62b0b0e2ff',
                        'label' => 'Montant',
                        'name' => 'atgp_reduc_montant',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-configuration',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    endif;
?>